#!/usr/bin/env python3
"""Classify a branch diff so a review can gate on what actually changed.

Emits JSON on stdout: per-file role + signals, which review aspects are active,
and a cost shape. Read-only; runs git and nothing else.

The point of doing this in a script rather than by model judgment: the review
report claims "aspect X did not run", and that claim has to be reproducible.
It also keeps the orchestrator from reading the whole diff (and forming
opinions) before it has to arbitrate between agents that did.

Exit codes: 0 ok · 2 not a git repo · 3 no base resolvable · 4 empty range.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys

SCHEMA = 1

# --------------------------------------------------------------------------
# git plumbing
# --------------------------------------------------------------------------


def git(repo: str, *args: str, check: bool = True) -> str:
    proc = subprocess.run(
        ["git", "-C", repo, *args],
        capture_output=True,
        text=True,
    )
    if check and proc.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {proc.stderr.strip()}")
    return proc.stdout


def resolve_base(repo: str, explicit: str | None) -> str | None:
    """Find the trunk this branch forked from.

    Deliberately NOT @{upstream}: on a pushed feature branch that resolves to
    the branch's own remote ref, and the diff collapses to whatever is
    uncommitted. We want "what this branch adds to the trunk", so trunk refs
    come first, and any candidate that is already an ancestor-equal of HEAD
    (i.e. we're standing on it) is skipped.
    """
    candidates = [explicit] if explicit else [
        "origin/HEAD", "origin/main", "origin/master", "main", "master", "@{upstream}"
    ]
    fallback = None
    for ref in candidates:
        if not ref:
            continue
        proc = subprocess.run(
            ["git", "-C", repo, "rev-parse", "--verify", "--quiet", f"{ref}^{{commit}}"],
            capture_output=True, text=True,
        )
        if proc.returncode != 0:
            continue
        if explicit:
            return ref
        sha = proc.stdout.strip()
        head = git(repo, "rev-parse", "HEAD").strip()
        merge_base = git(repo, "merge-base", ref, "HEAD", check=False).strip()
        if sha == head or merge_base == head:
            # We're on the trunk (or behind it) — this ref yields nothing useful.
            fallback = fallback or ref
            continue
        return ref
    return fallback


# --------------------------------------------------------------------------
# file roles
# --------------------------------------------------------------------------

LOCKFILES = {
    "Cargo.lock", "package-lock.json", "pnpm-lock.yaml", "yarn.lock", "go.sum",
    "poetry.lock", "uv.lock", "Gemfile.lock", "composer.lock", "Pipfile.lock",
    "gradle.lockfile", "flake.lock", "bun.lockb",
}

MANIFESTS = {
    "Cargo.toml", "package.json", "go.mod", "pyproject.toml", "setup.py",
    "build.gradle", "build.gradle.kts", "pom.xml", "Gemfile", "Pipfile",
    "composer.json",
}

WIRE_EXTS = {".proto", ".graphql", ".gql", ".thrift", ".avsc", ".smithy", ".raml"}
DOC_EXTS = {".md", ".mdx", ".rst", ".txt", ".adoc"}
CONFIG_EXTS = {".yaml", ".yml", ".toml", ".json", ".ini", ".cfg", ".properties"}

CODE_EXTS = {
    ".rs", ".go", ".py", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".java",
    ".kt", ".kts", ".scala", ".swift", ".c", ".h", ".cc", ".cpp", ".hpp", ".hh",
    ".cs", ".rb", ".php", ".ex", ".exs", ".erl", ".hs", ".ml", ".dart", ".lua",
    ".sh", ".bash", ".zsh", ".sql", ".vue", ".svelte", ".m", ".mm", ".zig",
    ".clj", ".cljs", ".jl", ".nim", ".pl", ".r",
}

GENERATED_DIR_RE = re.compile(
    r"(^|/)(target|dist|build|node_modules|vendor|gen|\.generated|__pycache__)/"
)
GENERATED_NAME_RE = re.compile(
    r"(\.pb\.go|_pb2\.py|_pb2\.pyi|_pb\.js|\.g\.dart|\.generated\.[^.]+|\.min\.js|"
    r"\.min\.css|\.freezed\.dart)$"
)
GENERATED_HEADER_RE = re.compile(
    r"@generated|Code generated .* DO NOT EDIT|autogenerated|AUTO-GENERATED", re.I
)
TEST_PATH_RE = re.compile(r"(^|/)(tests?|__tests__|spec|specs|testdata|fixtures)/")
TEST_NAME_RE = re.compile(
    r"(^test_.*|.*_test\.[^.]+$|.*\.test\.[^.]+$|.*\.spec\.[^.]+$|.*Test\.java$|"
    r".*Tests\.cs$|conftest\.py$)"
)
OPENAPI_NAME_RE = re.compile(r"(openapi|swagger|api-spec)[^/]*\.(ya?ml|json)$", re.I)


def classify_role(path: str, is_binary: bool, header: str) -> str:
    base = os.path.basename(path)
    _, ext = os.path.splitext(base)
    ext = ext.lower()

    if base in LOCKFILES:
        return "lockfile"
    if base in MANIFESTS or re.match(r"requirements.*\.txt$", base) or ext == ".csproj":
        return "manifest"
    if GENERATED_DIR_RE.search(path) or GENERATED_NAME_RE.search(base):
        return "generated"
    if header and GENERATED_HEADER_RE.search(header):
        return "generated"
    if ext in WIRE_EXTS or OPENAPI_NAME_RE.search(base):
        return "wire_contract"
    if TEST_PATH_RE.search(path) or TEST_NAME_RE.match(base):
        return "test"
    if ext in DOC_EXTS:
        return "docs"
    if is_binary:
        return "binary"
    if ext in CODE_EXTS:
        return "source"
    if base == "Dockerfile" or ext in {".tf", ".tfvars"} or base.startswith(".env"):
        return "config"
    if ext in CONFIG_EXTS:
        return "config"
    return "unknown"


LANG_BY_EXT = {
    ".rs": "rust", ".go": "go", ".py": "python", ".ts": "ts", ".tsx": "ts",
    ".js": "js", ".jsx": "js", ".java": "java", ".kt": "kotlin", ".swift": "swift",
    ".cs": "csharp", ".rb": "ruby", ".c": "c", ".h": "c", ".cc": "cpp",
    ".cpp": "cpp", ".hpp": "cpp", ".proto": "proto", ".graphql": "graphql",
    ".sql": "sql", ".sh": "shell",
}


# --------------------------------------------------------------------------
# signals — regex over changed lines only, never whole files
# --------------------------------------------------------------------------

# Public/exported surface. Deliberately shallow: no parsing, no language server.
# Indentation guard (<= 4 columns) keeps nested helpers out.
API_SURFACE_RES = [
    re.compile(r"^\s{0,4}pub(\([^)]*\))?\s+(fn|struct|enum|trait|type|const|static|mod|use)\b"),
    re.compile(r"^\s{0,4}impl\b.*\bfor\b"),
    re.compile(r"^\s{0,4}(func|type|var|const)\s+\(?[A-Z]"),
    re.compile(r"^\s{0,4}export\s+(default\s+)?\w"),
    re.compile(r"^\s{0,4}declare\s+\w"),
    re.compile(r"^(def|class)\s+[A-Za-z]"),
    re.compile(r"^\s{0,4}__all__\s*="),
    re.compile(r"^\s{0,4}(public|open|internal|protected)\s+\w"),
    re.compile(r"^\s{0,4}(def self\.|module |class )\w"),
]
API_ALWAYS_PATHS = re.compile(r"(\.pyi$|\.d\.ts$|(^|/)(include|api|pkg|public)/)")

CLI_RE = re.compile(
    r"add_argument\(|#\[(arg|clap|command)|Command::new|\.option\(|yargs|"
    r"cobra\.Command|@click\.|argparse|flag\.(String|Bool|Int|Duration)"
)
ROUTE_RE = re.compile(
    r"@(Get|Post|Put|Patch|Delete)Mapping|app\.(get|post|put|patch|delete)\(|"
    r"router\.(get|post|put|patch|delete|route)\(|#\[(get|post|put|patch|delete|route)|"
    r"@app\.route|http\.HandleFunc|\.route\(|HttpServer::new"
)

# Wire-contract breakage. A removed field line, a reservation, a renumbering,
# or a removed rpc. `reserved` alone is not a defect (it's the correct removal
# ritual) — it's a marker that something WAS removed, which the reviewer needs.
PROTO_FIELD_RE = re.compile(r"^\s*(repeated\s+|optional\s+|required\s+)?[\w.<>, ]+\s+(\w+)\s*=\s*(\d+)\s*;")
RESERVED_RE = re.compile(r"^\s*reserved\s+")
RPC_RE = re.compile(r"^\s*rpc\s+(\w+)")
# NOTE: OpenAPI files are classified as wire_contract by name, but no breakage
# detection runs on their hunks — a naive "removed required-list entry" regex
# matches any YAML list item and would flood wire_breaking with false positives.
# Real OpenAPI diffing is tracked in meta/IMPROVEMENTS.md.

BUILD_CONTRACT_FILES = re.compile(
    r"(^|/)(build\.rs|build\.gradle(\.kts)?|CMakeLists\.txt|Makefile|"
    r"buf\.gen\.ya?ml|codegen\.ya?ml|gulpfile\.js|webpack\.config\.js)$"
)

SEMVER_RE = re.compile(r"(\d+)\.(\d+)\.?(\d+)?")
DEP_LINE_RE = re.compile(r'^[+-]\s*"?([\w@/._-]+)"?\s*[:=]\s*.*?"?[\^~>=<]*(\d+\.\d+(\.\d+)?)')


def dep_bumps(hunk_lines: list[str]) -> list[str]:
    """Major bumps (or 0.x minor bumps, which are majors in practice)."""
    removed: dict[str, str] = {}
    added: dict[str, str] = {}
    for line in hunk_lines:
        m = DEP_LINE_RE.match(line)
        if not m:
            continue
        name, ver = m.group(1), m.group(2)
        (removed if line.startswith("-") else added)[name] = ver
    out = []
    for name, new in added.items():
        old = removed.get(name)
        if not old or old == new:
            continue
        o, n = SEMVER_RE.match(old), SEMVER_RE.match(new)
        if not o or not n:
            continue
        o_major, o_minor = int(o.group(1)), int(o.group(2))
        n_major, n_minor = int(n.group(1)), int(n.group(2))
        if n_major != o_major or (n_major == 0 and n_minor != o_minor):
            out.append(f"{name} {old} -> {new}")
    return out


def scan_signals(path: str, role: str, hunk_lines: list[str]) -> tuple[list[str], list[str], list[str]]:
    """Return (signals, evidence lines, notes)."""
    signals: set[str] = set()
    evidence: list[str] = []
    notes: list[str] = []

    def note_evidence(line: str) -> None:
        if len(evidence) < 6:
            evidence.append(line.rstrip()[:160])

    if BUILD_CONTRACT_FILES.search(path):
        signals.add("build_contract_touched")

    if role == "manifest":
        bumps = dep_bumps(hunk_lines)
        if bumps:
            signals.add("dep_major_bump")
            notes.extend(bumps)

    # Names that survive the diff. A proto field that moves into a oneof, or an
    # rpc that gets re-indented, shows up as removed+added — that is not
    # breakage, and flagging it trains the reviewer to ignore the signal.
    surviving: set[str] = set()
    if role == "wire_contract":
        for raw in hunk_lines:
            if not raw.startswith("+"):
                continue
            m = PROTO_FIELD_RE.match(raw[1:]) or RPC_RE.match(raw[1:])
            if m:
                surviving.add(m.group(1) if m.re is RPC_RE else m.group(2))

    for raw in hunk_lines:
        body = raw[1:]
        added = raw.startswith("+")

        if role in ("source", "wire_contract"):
            if API_ALWAYS_PATHS.search(path):
                signals.add("api_surface_touched")
            for rx in API_SURFACE_RES:
                if rx.search(body):
                    signals.add("api_surface_touched")
                    if added:
                        note_evidence(raw)
                    break
            if CLI_RE.search(body):
                signals.add("cli_surface_touched")
            if ROUTE_RE.search(body):
                signals.add("http_route_touched")

        if role == "wire_contract" and not added:
            fm, rm = PROTO_FIELD_RE.match(body), RPC_RE.match(body)
            gone = (fm and fm.group(2) not in surviving) or (rm and rm.group(1) not in surviving)
            if RESERVED_RE.match(body) or gone:
                signals.add("wire_breaking")
                note_evidence(raw)

    # A retained field whose number changed is breakage that neither side shows
    # alone — compare the removed and added field maps.
    if role == "wire_contract":
        old_nums, new_nums = {}, {}
        for raw in hunk_lines:
            m = PROTO_FIELD_RE.match(raw[1:])
            if m:
                (new_nums if raw.startswith("+") else old_nums)[m.group(2)] = m.group(3)
        for name, num in new_nums.items():
            if name in old_nums and old_nums[name] != num:
                signals.add("wire_breaking")
                notes.append(f"{path}: field '{name}' renumbered {old_nums[name]} -> {num}")

    return sorted(signals), evidence, notes


# --------------------------------------------------------------------------
# diff parsing
# --------------------------------------------------------------------------


def parse_numstat(text: str) -> dict[str, tuple[int | None, int | None]]:
    out: dict[str, tuple[int | None, int | None]] = {}
    for line in text.splitlines():
        parts = line.split("\t")
        if len(parts) < 3:
            continue
        add, rem, path = parts[0], parts[1], parts[-1]
        binary = add == "-" or rem == "-"
        out[path] = (None, None) if binary else (int(add), int(rem))
    return out


def parse_name_status(text: str) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in text.splitlines():
        parts = line.split("\t")
        if len(parts) < 2:
            continue
        out[parts[-1]] = parts[0][0]
    return out


def split_patch_by_file(patch: str) -> dict[str, list[str]]:
    """Map path -> changed lines (with leading +/-), ignoring hunk headers."""
    files: dict[str, list[str]] = {}
    current: str | None = None
    for line in patch.splitlines():
        if line.startswith("diff --git "):
            m = re.search(r" b/(.+)$", line)
            current = m.group(1) if m else None
            if current:
                files.setdefault(current, [])
        elif current and line.startswith(("+", "-")):
            if line.startswith(("+++", "---")):
                continue
            files[current].append(line)
    return files


def file_header(repo: str, path: str, limit: int = 30) -> str:
    full = os.path.join(repo, path)
    try:
        with open(full, "r", encoding="utf-8", errors="replace") as fh:
            return "".join(next(fh, "") for _ in range(limit))
    except OSError:
        return ""


# --------------------------------------------------------------------------
# aspects and shape
# --------------------------------------------------------------------------


def compute_aspects(files: list[dict]) -> dict:
    def has(sig: str) -> list[str]:
        return [f["path"] for f in files if sig in f["signals"]]

    wire_files = [f for f in files if f["role"] == "wire_contract"]
    breaking = has("wire_breaking")
    routes = has("http_route_touched")
    clis = has("cli_surface_touched")
    build = has("build_contract_touched")
    api_files = [
        f["path"] for f in files
        if "api_surface_touched" in f["signals"] and f["role"] != "generated"
    ]
    new_source = [f["path"] for f in files if f["status"] == "A" and f["role"] == "source"]
    new_modules = has("new_module")

    code = [f for f in files if f["role"] in ("source", "wire_contract")]
    code_lines = sum((f["added"] or 0) + (f["removed"] or 0) for f in code)

    aspects = {}

    # build/codegen contracts count: a four-line change to build.rs can alter every
    # generated type in a package. Omitting it here while still listing it in
    # `files` and `why` left the aspect inactive on a pure-codegen change.
    wire_active = bool(wire_files or routes or clis or build)
    wire_why = []
    if wire_files:
        wire_why.append(f"{len(wire_files)} wire-contract file(s) changed")
    if breaking:
        wire_why.append(f"wire_breaking in {', '.join(breaking)}")
    if routes:
        wire_why.append(f"{len(routes)} file(s) with route changes")
    if clis:
        wire_why.append(f"{len(clis)} file(s) with CLI surface changes")
    if build:
        wire_why.append(f"build/codegen contract touched: {', '.join(build)}")
    aspects["wire_api"] = {
        "active": wire_active,
        "strength": "strong" if (breaking or any(f["status"] == "A" for f in wire_files)) else "weak",
        "why": "; ".join(wire_why) or "no wire contract, route, or CLI changes",
        "files": sorted({f["path"] for f in wire_files} | set(routes) | set(clis) | set(build)),
    }

    aspects["code_api"] = {
        "active": bool(api_files),
        "strength": "strong" if (len(api_files) >= 3 or new_source) else "weak",
        "why": (
            f"{len(api_files)} file(s) changed exported surface"
            + (f"; {len(new_source)} new source file(s)" if new_source else "")
        ) if api_files else "no exported surface changed",
        "files": sorted(api_files),
    }

    aspects["logic"] = {
        "active": code_lines >= 25,
        "strength": "strong" if code_lines >= 150 else "weak",
        "why": f"{code_lines} changed line(s) in source/wire files (threshold 25)",
        "files": sorted(f["path"] for f in code),
    }

    conv_files = sorted(set(new_source) | set(new_modules))
    new_dirs = {os.path.dirname(p) for p in new_source}
    existing_dirs = {os.path.dirname(f["path"]) for f in files if f["status"] != "A"}
    whole_new_dir = bool(new_dirs - existing_dirs)
    aspects["convention"] = {
        "active": bool(conv_files),
        "strength": "strong" if whole_new_dir else "weak",
        "why": (
            f"{len(new_source)} new source file(s)"
            + ("; a whole new directory appeared" if whole_new_dir else "")
        ) if conv_files else "no new code — conventions are only audited on new code",
        "files": conv_files,
    }

    return aspects


def compute_shape(code_files: int, code_lines: int) -> str:
    """Pick the cost shape from how much code actually changed.

    `focused` keys on line count alone. The shape exists to answer "does the
    whole diff fit in the orchestrator's context, such that delegating costs
    more than it saves" — and that is a question about volume, not spread.
    Requiring few files as well misclassified a 500-line single-file rewrite as
    small; requiring both (`and`) would misclassify a 40-line change spread over
    eight files as large. File count only matters for `deep`, where sharding by
    directory needs directories to shard by.
    """
    if code_lines > 2000 or code_files > 40:
        return "deep"
    if code_lines < 150:
        return "focused"
    return "standard"


# --------------------------------------------------------------------------


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--base", help="base ref (default: upstream -> origin/HEAD -> main -> master)")
    ap.add_argument("--repo", default=".", help="repo path (default: cwd)")
    ap.add_argument("--no-untracked", action="store_true", help="skip untracked files")
    ap.add_argument("--max-file-bytes", type=int, default=400_000)
    ap.add_argument("--pretty", action="store_true")
    args = ap.parse_args()

    repo = os.path.abspath(args.repo)
    try:
        git(repo, "rev-parse", "--git-dir")
    except RuntimeError:
        print(json.dumps({"error": "not a git repository", "repo": repo}), file=sys.stderr)
        return 2

    base = resolve_base(repo, args.base)
    if not base:
        print(json.dumps({"error": "no base ref resolvable"}), file=sys.stderr)
        return 3

    merge_base = git(repo, "merge-base", base, "HEAD").strip()
    head = git(repo, "rev-parse", "HEAD").strip()

    # One range covering committed AND uncommitted work: `git diff <merge-base>`
    # with no second ref compares against the working tree. That is what puts a
    # not-yet-committed debug line in scope, which is often exactly what you
    # want caught before it ships.
    numstat = parse_numstat(git(repo, "diff", "--numstat", merge_base))
    status = parse_name_status(git(repo, "diff", "--name-status", merge_base))
    patch = git(repo, "diff", "--unified=0", merge_base)
    hunks = split_patch_by_file(patch)
    # These are independent facts, not alternatives: a file can be added in a
    # commit on this branch AND further edited in the working tree. The report
    # needs both, because only committed hunks can carry inline PR comments.
    worktree_paths = set(parse_name_status(git(repo, "diff", "--name-status", "HEAD")))
    committed_paths = set(parse_name_status(git(repo, "diff", "--name-status", merge_base, "HEAD")))

    untracked: list[str] = []
    if not args.no_untracked:
        untracked = [
            p for p in git(repo, "ls-files", "--others", "--exclude-standard").splitlines() if p
        ]

    dirty = bool(worktree_paths or untracked)
    all_paths = sorted(set(numstat) | set(untracked))
    if not all_paths:
        print(json.dumps({"error": "empty range", "base": base, "merge_base": merge_base}), file=sys.stderr)
        return 4

    files: list[dict] = []
    notes: list[str] = []
    excluded: dict[str, int] = {}

    for path in all_paths:
        is_untracked = path in untracked and path not in numstat
        added, removed = numstat.get(path, (0, 0))
        is_binary = added is None
        added = added or 0
        removed = removed or 0

        full = os.path.join(repo, path)
        try:
            size = os.path.getsize(full)
        except OSError:
            size = 0
        too_big = size > args.max_file_bytes

        header = "" if (is_binary or too_big) else file_header(repo, path)
        role = classify_role(path, is_binary, header)

        lines = [] if too_big else hunks.get(path, [])
        if is_untracked and role != "binary":
            # Untracked files aren't in --numstat, so their size has to come from
            # the file itself. Oversized ones still get counted — just line-counted
            # rather than read into memory and regex-scanned — otherwise a large new
            # file is invisible to both the shape selector and aspect gating while
            # the note claims it was counted.
            try:
                if too_big:
                    with open(full, "rb") as fh:
                        added = sum(1 for _ in fh)
                else:
                    with open(full, "r", encoding="utf-8", errors="replace") as fh:
                        body = fh.readlines()
                    lines = ["+" + line for line in body]
                    added = len(body)
            except OSError:
                pass

        if too_big:
            notes.append(
                f"{path}: {size} bytes exceeds --max-file-bytes; "
                f"{added} lines counted, content not scanned for signals"
            )

        signals, evidence, file_notes = scan_signals(path, role, lines)
        notes.extend(file_notes)

        if role not in ("source", "wire_contract"):
            excluded[role] = excluded.get(role, 0) + added + removed

        st = "A" if is_untracked else status.get(path, "M")
        if st == "A" and role == "source":
            signals = sorted(set(signals) | {"new_module"})

        files.append({
            "path": path,
            "status": st,
            "role": role,
            "lang": LANG_BY_EXT.get(os.path.splitext(path)[1].lower()),
            "added": added,
            "removed": removed,
            "committed": path in committed_paths,
            "worktree": path in worktree_paths or is_untracked,
            "signals": signals,
            "evidence": evidence,
        })

    code = [f for f in files if f["role"] in ("source", "wire_contract")]
    code_lines = sum(f["added"] + f["removed"] for f in code)
    aspects = compute_aspects(files)
    shape = compute_shape(len(code), code_lines)

    if excluded.get("lockfile"):
        notes.append(
            f"lockfile churn excluded from code_lines ({excluded['lockfile']} lines) — "
            "dependency waves must not inflate the cost shape or activate logic review"
        )

    result = {
        "schema": SCHEMA,
        "base": base,
        "merge_base": merge_base,
        "head": head,
        "dirty": dirty,
        "totals": {
            "files": len(files),
            "insertions": sum(f["added"] for f in files),
            "deletions": sum(f["removed"] for f in files),
            "code_files": len(code),
            "code_lines": code_lines,
            "excluded": excluded,
        },
        "files": files,
        "aspects": aspects,
        "shape": shape,
        "notes": notes,
    }

    json.dump(result, sys.stdout, indent=2 if args.pretty else None)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
