#!/usr/bin/env python3
"""Tests for scope_detect.py.

The matrix is built from the *branches of the code*, not from convenient repos —
that's the lesson from PR #1, where two passing fixtures missed three real bugs
(untracked files, oversized files, single-file diffs). Every role, every signal,
every aspect-activation predicate, both shape boundaries, and the git-plumbing
edge cases each get a case here.

Pure functions are tested directly (fast, exhaustive); everything that needs git
state runs against small synthetic repos built per-test in a tempdir.

Run:  python3 test_scope_detect.py            (stdlib only, no pytest needed)
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPT = os.path.join(HERE, "scope_detect.py")
sys.path.insert(0, HERE)

import scope_detect as sd  # noqa: E402


# --------------------------------------------------------------------------
# classify_role — one case per role branch, plus precedence collisions
# --------------------------------------------------------------------------

class TestClassifyRole(unittest.TestCase):
    CASES = [
        # (path, is_binary, header, expected)
        ("Cargo.lock", False, "", "lockfile"),
        ("web/pnpm-lock.yaml", False, "", "lockfile"),
        ("Cargo.toml", False, "", "manifest"),
        ("requirements-dev.txt", False, "", "manifest"),   # beats DOC_EXTS .txt
        ("App.csproj", False, "", "manifest"),
        ("target/debug/foo.rs", False, "", "generated"),   # generated dir
        ("api_pb2.py", False, "", "generated"),            # generated name
        ("gen/schema.proto", False, "", "generated"),      # gen dir beats wire ext
        ("src/models.rs", False, "// @generated by tool\n", "generated"),  # header
        ("proto/user.proto", False, "", "wire_contract"),
        ("api/openapi.v1.yaml", False, "", "wire_contract"),  # OPENAPI name beats config ext
        ("swagger.json", False, "", "wire_contract"),
        ("tests/integration.rs", False, "", "test"),       # test dir
        ("tests/data.json", False, "", "test"),            # test dir beats config ext
        ("src/foo_test.go", False, "", "test"),            # test name
        ("src/Foo.test.ts", False, "", "test"),
        ("conftest.py", False, "", "test"),
        # Documented quirk, not necessarily desired: helper modules named
        # test_*.py classify as tests (TODO P3 #11). Pin current behavior.
        ("src/test_utils.py", False, "", "test"),
        ("docs/guide.md", False, "", "docs"),
        ("notes.adoc", False, "", "docs"),
        ("logo.png", True, "", "binary"),
        ("src/main.rs", False, "", "source"),
        ("scripts/run.sh", False, "", "source"),
        ("Dockerfile", False, "", "config"),
        ("infra/main.tf", False, "", "config"),
        (".env.production", False, "", "config"),
        ("settings.yaml", False, "", "config"),
        ("data.bin", False, "", "unknown"),
    ]

    def test_roles(self):
        for path, is_binary, header, want in self.CASES:
            got = sd.classify_role(path, is_binary, header)
            self.assertEqual(got, want, f"{path}: want {want}, got {got}")


# --------------------------------------------------------------------------
# dep_bumps — the semver logic, both manifest styles
# --------------------------------------------------------------------------

class TestDepBumps(unittest.TestCase):
    def bumps(self, lines):
        return sd.dep_bumps(lines)

    def test_major_bump_toml(self):
        out = self.bumps(['-alpha = "1.2.3"', '+alpha = "2.0.0"'])
        self.assertEqual(out, ["alpha 1.2.3 -> 2.0.0"])

    def test_zero_x_minor_is_major(self):
        out = self.bumps(['-beta = "0.12.4"', '+beta = "0.13.0"'])
        self.assertEqual(out, ["beta 0.12.4 -> 0.13.0"])

    def test_minor_and_patch_are_not_bumps(self):
        self.assertEqual(self.bumps(['-a = "1.2.0"', '+a = "1.3.0"']), [])
        self.assertEqual(self.bumps(['-a = "1.2.0"', '+a = "1.2.9"']), [])

    def test_zero_x_patch_is_not_a_bump(self):
        self.assertEqual(self.bumps(['-a = "0.12.4"', '+a = "0.12.9"']), [])

    def test_package_json_style(self):
        out = self.bumps(['-  "left-pad": "^1.3.0",', '+  "left-pad": "^2.0.1",'])
        self.assertEqual(out, ["left-pad 1.3.0 -> 2.0.1"])

    def test_added_without_removed_is_not_a_bump(self):
        self.assertEqual(self.bumps(['+newdep = "3.0.0"']), [])

    def test_unparseable_lines_ignored(self):
        self.assertEqual(self.bumps(["-[dependencies]", "+[dependencies]"]), [])


# --------------------------------------------------------------------------
# scan_signals — API surface per language, CLI, routes, wire breakage
# --------------------------------------------------------------------------

class TestScanSignals(unittest.TestCase):
    def signals(self, path, role, lines):
        sig, _ev, notes = sd.scan_signals(path, role, lines)
        return sig, notes

    def test_api_surface_across_languages(self):
        for line in [
            "+pub fn connect() -> Client {",       # rust
            "+pub(crate) struct Config {",         # rust scoped
            "+func NewServer(cfg Config) *Server", # go exported
            "+export default class Widget {",      # ts/js
            "+def handle(request):",               # python top-level
            "+class Parser:",                      # python class
            "+__all__ = ['x']",                    # python export list
            "+public String getName() {",          # java
        ]:
            sig, _ = self.signals("src/lib.rs", "source", [line])
            self.assertIn("api_surface_touched", sig, f"missed: {line!r}")

    def test_removed_surface_still_signals(self):
        # A deleted export is an API change too; only *evidence* is added-only.
        sig, _ = self.signals("src/lib.rs", "source", ["-pub fn gone() {}"])
        self.assertIn("api_surface_touched", sig)

    def test_nested_helper_does_not_signal(self):
        sig, _ = self.signals("src/lib.rs", "source", ["+        pub fn inner() {}"])
        self.assertNotIn("api_surface_touched", sig)

    def test_api_always_paths(self):
        for path in ["types/foo.d.ts", "stubs/mod.pyi", "include/header.h", "pkg/client.go"]:
            sig, _ = self.signals(path, "source", ["+x = 1"])
            self.assertIn("api_surface_touched", sig, path)

    def test_cli_and_route_surface(self):
        sig, _ = self.signals("src/cli.py", "source", ['+parser.add_argument("--force")'])
        self.assertIn("cli_surface_touched", sig)
        sig, _ = self.signals("src/http.ts", "source", ['+app.get("/users", listUsers)'])
        self.assertIn("http_route_touched", sig)
        sig, _ = self.signals("src/main.go", "source", ['+http.HandleFunc("/health", ok)'])
        self.assertIn("http_route_touched", sig)

    def test_signals_gated_to_code_roles(self):
        sig, _ = self.signals("README.md", "docs", ["+pub fn x() {}"])
        self.assertEqual(sig, [])

    def test_wire_breaking_on_removed_field(self):
        sig, _ = self.signals("a.proto", "wire_contract", ["-  string email = 4;"])
        self.assertIn("wire_breaking", sig)

    def test_wire_breaking_on_reserved(self):
        sig, _ = self.signals("a.proto", "wire_contract", ["-reserved 7;"])
        # `reserved` on a removed line marks that a removal happened.
        self.assertIn("wire_breaking", sig)

    def test_moved_field_is_not_breaking(self):
        # Field relocated (e.g. into a oneof): removed+added with same name.
        sig, _ = self.signals("a.proto", "wire_contract",
                              ["-  string email = 4;", "+    string email = 4;"])
        self.assertNotIn("wire_breaking", sig)

    def test_moved_rpc_is_not_breaking(self):
        sig, _ = self.signals("a.proto", "wire_contract",
                              ["-  rpc GetUser(Req) returns (Resp);",
                               "+    rpc GetUser(Req) returns (Resp);"])
        self.assertNotIn("wire_breaking", sig)

    def test_removed_rpc_is_breaking(self):
        sig, _ = self.signals("a.proto", "wire_contract",
                              ["-  rpc DeleteUser(Req) returns (Resp);"])
        self.assertIn("wire_breaking", sig)

    def test_renumbered_field_is_breaking_with_note(self):
        sig, notes = self.signals("a.proto", "wire_contract",
                                  ["-  string email = 4;", "+  string email = 5;"])
        self.assertIn("wire_breaking", sig)
        self.assertTrue(any("renumbered 4 -> 5" in n for n in notes), notes)

    def test_build_contract_touched(self):
        for path in ["build.rs", "svc/buf.gen.yaml", "app/build.gradle.kts", "Makefile"]:
            sig, _ = self.signals(path, "source", [])
            self.assertIn("build_contract_touched", sig, path)

    def test_manifest_bump_lands_in_notes(self):
        _, notes = self.signals("Cargo.toml", "manifest",
                                ['-x = "1.0.0"', '+x = "2.0.0"'])
        self.assertEqual(notes, ["x 1.0.0 -> 2.0.0"])


# --------------------------------------------------------------------------
# compute_shape — both boundaries, and the two PR-#1 regression cases
# --------------------------------------------------------------------------

class TestComputeShape(unittest.TestCase):
    CASES = [
        # (code_files, code_lines, expected)
        (1, 149, "focused"),
        (1, 150, "standard"),
        (8, 40, "focused"),      # spread-out but tiny: volume rules, not file count
        (1, 500, "standard"),    # PR #1 bug 3: single-file rewrite is NOT focused
        (5, 2000, "standard"),
        (5, 2001, "deep"),
        (41, 10, "deep"),        # file count alone can force deep (sharding needs dirs)
        (40, 10, "focused"),
    ]

    def test_boundaries(self):
        for files, lines, want in self.CASES:
            self.assertEqual(sd.compute_shape(files, lines), want, (files, lines))


# --------------------------------------------------------------------------
# compute_aspects — every activation predicate and strength rule
# --------------------------------------------------------------------------

def f(path, role="source", status="M", signals=(), added=10, removed=0):
    return {"path": path, "role": role, "status": status,
            "signals": sorted(signals), "added": added, "removed": removed}


class TestComputeAspects(unittest.TestCase):
    def test_all_inactive_on_dep_bump(self):
        files = [f("Cargo.toml", role="manifest", signals=["dep_major_bump"]),
                 f("Cargo.lock", role="lockfile", added=900)]
        a = sd.compute_aspects(files)
        for name in ("wire_api", "code_api", "logic", "convention"):
            self.assertFalse(a[name]["active"], name)

    def test_wire_active_via_contract_file(self):
        a = sd.compute_aspects([f("u.proto", role="wire_contract")])
        self.assertTrue(a["wire_api"]["active"])
        self.assertEqual(a["wire_api"]["strength"], "weak")  # modified, not breaking

    def test_wire_strong_on_breaking(self):
        a = sd.compute_aspects([f("u.proto", role="wire_contract",
                                  signals=["wire_breaking"])])
        self.assertEqual(a["wire_api"]["strength"], "strong")

    def test_wire_strong_on_new_contract(self):
        a = sd.compute_aspects([f("u.proto", role="wire_contract", status="A")])
        self.assertEqual(a["wire_api"]["strength"], "strong")

    def test_wire_active_via_routes_and_cli(self):
        a = sd.compute_aspects([f("s.py", signals=["http_route_touched"])])
        self.assertTrue(a["wire_api"]["active"])
        a = sd.compute_aspects([f("c.py", signals=["cli_surface_touched"])])
        self.assertTrue(a["wire_api"]["active"])

    def test_wire_active_via_build_contract_alone(self):
        # PR #1 bug 1: a pure build.rs change must activate wire_api.
        a = sd.compute_aspects([f("build.rs", signals=["build_contract_touched"])])
        self.assertTrue(a["wire_api"]["active"])
        self.assertIn("build.rs", a["wire_api"]["files"])

    def test_code_api_activation_and_strength(self):
        one = [f("a.rs", signals=["api_surface_touched"])]
        self.assertTrue(sd.compute_aspects(one)["code_api"]["active"])
        self.assertEqual(sd.compute_aspects(one)["code_api"]["strength"], "weak")

        three = [f(p, signals=["api_surface_touched"]) for p in ("a.rs", "b.rs", "c.rs")]
        self.assertEqual(sd.compute_aspects(three)["code_api"]["strength"], "strong")

        new = [f("a.rs", status="A", signals=["api_surface_touched", "new_module"])]
        self.assertEqual(sd.compute_aspects(new)["code_api"]["strength"], "strong")

    def test_generated_files_do_not_activate_code_api(self):
        a = sd.compute_aspects([f("x_pb2.py", role="generated",
                                  signals=["api_surface_touched"])])
        self.assertFalse(a["code_api"]["active"])

    def test_logic_threshold(self):
        self.assertFalse(sd.compute_aspects([f("a.rs", added=24)])["logic"]["active"])
        on = sd.compute_aspects([f("a.rs", added=25)])["logic"]
        self.assertTrue(on["active"])
        self.assertEqual(on["strength"], "weak")
        self.assertEqual(sd.compute_aspects([f("a.rs", added=150)])["logic"]["strength"],
                         "strong")

    def test_logic_counts_only_code_roles(self):
        files = [f("Cargo.lock", role="lockfile", added=5000),
                 f("README.md", role="docs", added=500),
                 f("a.rs", added=10)]
        self.assertFalse(sd.compute_aspects(files)["logic"]["active"])

    def test_logic_removed_lines_count(self):
        a = sd.compute_aspects([f("a.rs", added=0, removed=30)])
        self.assertTrue(a["logic"]["active"])

    def test_convention_only_on_new_code(self):
        self.assertFalse(sd.compute_aspects([f("a.rs")])["convention"]["active"])
        a = sd.compute_aspects([f("src/new.rs", status="A", signals=["new_module"])])
        self.assertTrue(a["convention"]["active"])

    def test_convention_strong_only_for_whole_new_dir(self):
        # New file in a directory that also has modified files → weak.
        mixed = [f("src/new.rs", status="A", signals=["new_module"]), f("src/old.rs")]
        self.assertEqual(sd.compute_aspects(mixed)["convention"]["strength"], "weak")
        # New file whose directory contains nothing pre-existing → strong.
        fresh = [f("src/alerts/mod.rs", status="A", signals=["new_module"]),
                 f("src/old.rs")]
        self.assertEqual(sd.compute_aspects(fresh)["convention"]["strength"], "strong")


# --------------------------------------------------------------------------
# diff parsing helpers
# --------------------------------------------------------------------------

class TestParsers(unittest.TestCase):
    def test_parse_numstat_binary(self):
        out = sd.parse_numstat("12\t3\tsrc/a.rs\n-\t-\tlogo.png\n")
        self.assertEqual(out["src/a.rs"], (12, 3))
        self.assertEqual(out["logo.png"], (None, None))

    def test_parse_name_status_rename(self):
        out = sd.parse_name_status("M\tsrc/a.rs\nR100\told.rs\tnew.rs\n")
        self.assertEqual(out["src/a.rs"], "M")
        self.assertEqual(out["new.rs"], "R")  # rename keyed by new path

    def test_split_patch_by_file(self):
        patch = (
            "diff --git a/x.rs b/x.rs\n--- a/x.rs\n+++ b/x.rs\n"
            "@@ -1 +1 @@\n-old\n+new\n"
            "diff --git a/y.rs b/y.rs\n--- a/y.rs\n+++ b/y.rs\n"
            "@@ -0,0 +1 @@\n+added\n"
        )
        out = sd.split_patch_by_file(patch)
        self.assertEqual(out["x.rs"], ["-old", "+new"])
        self.assertEqual(out["y.rs"], ["+added"])


# --------------------------------------------------------------------------
# integration — synthetic git repos
# --------------------------------------------------------------------------

GIT_ENV = {**os.environ,
           "GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@t",
           "GIT_COMMITTER_NAME": "t", "GIT_COMMITTER_EMAIL": "t@t",
           "GIT_CONFIG_GLOBAL": "/dev/null", "GIT_CONFIG_SYSTEM": "/dev/null"}


def git(repo, *args):
    subprocess.run(["git", "-C", repo, *args], check=True,
                   capture_output=True, text=True, env=GIT_ENV)


def put(repo, rel, content):
    full = os.path.join(repo, rel)
    os.makedirs(os.path.dirname(full) or full, exist_ok=True) if os.path.dirname(rel) \
        else None
    with open(full, "w") as fh:
        fh.write(content)


def run_scope(repo, *args):
    proc = subprocess.run([sys.executable, SCRIPT, "--repo", repo, *args],
                          capture_output=True, text=True)
    data = json.loads(proc.stdout) if proc.returncode == 0 and proc.stdout else None
    return proc.returncode, data, proc.stderr


class IntegrationBase(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.dir = self._tmp.name

    def tearDown(self):
        self._tmp.cleanup()

    def make_repo(self, name="repo", branch="main"):
        repo = os.path.join(self.dir, name)
        os.makedirs(repo)
        git(repo, "init", "-q", "-b", branch)
        return repo


class TestExitCodes(IntegrationBase):
    def test_not_a_repo_is_2(self):
        plain = os.path.join(self.dir, "plain")
        os.makedirs(plain)
        code, _, err = run_scope(plain)
        self.assertEqual(code, 2, err)

    def test_no_base_is_3(self):
        repo = self.make_repo(branch="work")  # no main/master, no remotes
        put(repo, "a.txt", "x\n")
        git(repo, "add", "."); git(repo, "commit", "-qm", "init")
        code, _, err = run_scope(repo)
        self.assertEqual(code, 3, err)

    def test_empty_range_is_4(self):
        repo = self.make_repo()  # standing on main, clean tree
        put(repo, "a.txt", "x\n")
        git(repo, "add", "."); git(repo, "commit", "-qm", "init")
        code, _, err = run_scope(repo)
        self.assertEqual(code, 4, err)


class TestBranchReview(IntegrationBase):
    """One feature branch exercising committed+worktree+untracked at once."""

    def build(self):
        repo = self.make_repo()
        put(repo, "src/lib.rs", "fn private() {}\n")
        put(repo, "Cargo.toml", '[dependencies]\nserde = "1.0.0"\n')
        put(repo, "Cargo.lock", "# lock\n" + "line\n" * 50)
        git(repo, "add", "."); git(repo, "commit", "-qm", "init")
        git(repo, "checkout", "-qb", "feat")
        # committed: exported surface + dep major bump + lockfile churn
        put(repo, "src/lib.rs", "fn private() {}\npub fn api() {}\n")
        put(repo, "Cargo.toml", '[dependencies]\nserde = "2.0.0"\n')
        put(repo, "Cargo.lock", "# lock\n" + "other\n" * 300)
        put(repo, "src/alerts/mod.rs", "pub fn alert() {}\n")
        git(repo, "add", "."); git(repo, "commit", "-qm", "feature")
        # worktree edit on an already-committed file
        put(repo, "src/lib.rs", "fn private() {}\npub fn api() {}\n// wip\n")
        # untracked new file
        put(repo, "src/extra.rs", "pub fn extra() {}\n")
        return repo

    def test_full_classification(self):
        repo = self.build()
        code, data, err = run_scope(repo)
        self.assertEqual(code, 0, err)
        by_path = {x["path"]: x for x in data["files"]}

        lib = by_path["src/lib.rs"]
        self.assertTrue(lib["committed"] and lib["worktree"],
                        "a file changed in a commit AND the worktree is both")
        self.assertIn("api_surface_touched", lib["signals"])

        extra = by_path["src/extra.rs"]
        self.assertEqual(extra["status"], "A")
        self.assertFalse(extra["committed"])
        self.assertTrue(extra["worktree"])
        self.assertIn("new_module", extra["signals"])
        self.assertGreater(extra["added"], 0, "untracked files must be line-counted")

        self.assertEqual(by_path["Cargo.lock"]["role"], "lockfile")
        self.assertIn("dep_major_bump", by_path["Cargo.toml"]["signals"])
        self.assertTrue(any("serde 1.0.0 -> 2.0.0" in n for n in data["notes"]))

        self.assertTrue(data["dirty"])
        # lockfile churn excluded from code_lines
        self.assertLess(data["totals"]["code_lines"], 50)
        self.assertGreaterEqual(data["totals"]["excluded"].get("lockfile", 0), 300)
        self.assertTrue(any("lockfile churn excluded" in n for n in data["notes"]))

        self.assertTrue(data["aspects"]["code_api"]["active"])
        self.assertTrue(data["aspects"]["convention"]["active"])
        self.assertEqual(data["aspects"]["convention"]["strength"], "strong",
                         "src/alerts/ is a whole new directory")
        self.assertFalse(data["aspects"]["wire_api"]["active"])

    def test_no_untracked_flag(self):
        repo = self.build()
        code, data, err = run_scope(repo, "--no-untracked")
        self.assertEqual(code, 0, err)
        self.assertNotIn("src/extra.rs", {x["path"] for x in data["files"]})


class TestOversizedUntracked(IntegrationBase):
    def test_counted_not_scanned(self):
        # PR #1 bug 2: oversized untracked files must still be line-counted.
        repo = self.make_repo()
        put(repo, "a.txt", "x\n")
        git(repo, "add", "."); git(repo, "commit", "-qm", "init")
        git(repo, "checkout", "-qb", "feat")
        put(repo, "src/huge.rs", "pub fn x() {}\n" * 200)  # ~2800 bytes
        code, data, err = run_scope(repo, "--max-file-bytes", "1000")
        self.assertEqual(code, 0, err)
        huge = next(x for x in data["files"] if x["path"] == "src/huge.rs")
        self.assertEqual(huge["added"], 200)
        # `new_module` is status-derived (the file is added); everything
        # content-derived must be absent because the body was never scanned.
        self.assertEqual([s for s in huge["signals"] if s != "new_module"], [],
                         "oversized files are counted but never regex-scanned")
        self.assertTrue(any("not scanned" in n for n in data["notes"]))
        self.assertTrue(data["aspects"]["logic"]["active"],
                        "200 counted lines must reach the logic gate")


class TestBaseResolution(IntegrationBase):
    def test_prefers_trunk_over_upstream(self):
        # Iteration-1 bug 1: on a pushed feature branch, @{upstream} resolves to
        # the branch's own remote ref and the diff collapses to uncommitted work.
        src = self.make_repo("src")
        put(src, "a.rs", "fn a() {}\n")
        git(src, "add", "."); git(src, "commit", "-qm", "init")
        bare = os.path.join(self.dir, "bare.git")
        subprocess.run(["git", "clone", "-q", "--bare", src, bare],
                       check=True, capture_output=True, env=GIT_ENV)
        work = os.path.join(self.dir, "work")
        subprocess.run(["git", "clone", "-q", bare, work],
                       check=True, capture_output=True, env=GIT_ENV)
        git(work, "checkout", "-qb", "feat")
        put(work, "a.rs", "fn a() {}\npub fn b() {}\n")
        git(work, "add", "."); git(work, "commit", "-qm", "feature")
        git(work, "push", "-qu", "origin", "feat")

        code, data, err = run_scope(work)
        self.assertEqual(code, 0, err)
        self.assertIn(data["base"], ("origin/HEAD", "origin/main"),
                      f"base must be the trunk, not @{{upstream}}; got {data['base']}")
        self.assertIn("a.rs", {x["path"] for x in data["files"]},
                      "the committed change must be in scope")

    def test_explicit_base(self):
        repo = self.make_repo()
        put(repo, "a.rs", "fn a() {}\n")
        git(repo, "add", "."); git(repo, "commit", "-qm", "init")
        git(repo, "branch", "-q", "release")
        git(repo, "checkout", "-qb", "feat")
        put(repo, "a.rs", "fn a() {}\npub fn b() {}\n")
        git(repo, "add", "."); git(repo, "commit", "-qm", "feature")
        code, data, err = run_scope(repo, "--base", "release")
        self.assertEqual(code, 0, err)
        self.assertEqual(data["base"], "release")


class TestWireEndToEnd(IntegrationBase):
    def test_breaking_proto_activates_strong_wire(self):
        repo = self.make_repo()
        put(repo, "proto/user.proto",
            'syntax = "proto3";\nmessage User {\n  string name = 1;\n'
            '  string email = 2;\n}\n')
        git(repo, "add", "."); git(repo, "commit", "-qm", "init")
        git(repo, "checkout", "-qb", "feat")
        put(repo, "proto/user.proto",
            'syntax = "proto3";\nmessage User {\n  string name = 1;\n'
            '  reserved 2;\n}\n')
        git(repo, "add", "."); git(repo, "commit", "-qm", "drop email")
        code, data, err = run_scope(repo)
        self.assertEqual(code, 0, err)
        wire = data["aspects"]["wire_api"]
        self.assertTrue(wire["active"])
        self.assertEqual(wire["strength"], "strong")
        proto = next(x for x in data["files"] if x["path"] == "proto/user.proto")
        self.assertIn("wire_breaking", proto["signals"])


if __name__ == "__main__":
    unittest.main(verbosity=2)
